In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# Numpy
import numpy as np     # np is short form for numpy

In [3]:
a=np.array([4,9,3,89,6])

In [4]:
type(a)

numpy.ndarray

In [5]:
a[-2],a[3]

(89, 89)

In [6]:
a[0:3:2]

array([4, 3])

In [7]:
a[1:4:]

array([ 9,  3, 89])

In [8]:
a[-2:-5:-1],a[-2:0:-1]

(array([89,  3,  9]), array([89,  3,  9]))

In [9]:
a[::4]

array([4, 6])

In [10]:
a[-1:-6:-4]

array([6, 4])

In [11]:
a=np.array([7,9,45,4.5,12.8],dtype="int")

In [12]:
a

array([ 7,  9, 45,  4, 12])

In [13]:
a = np.arange(4,9,1) # start, end, increment value by

In [14]:
a

array([4, 5, 6, 7, 8])

In [15]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
a.ndim #dimension

1

In [17]:
#creating 2-D array
a1=np.array([[7,8],[9,5],[3,8]])

In [18]:
a1

array([[7, 8],
       [9, 5],
       [3, 8]])

In [19]:
a1.ndim

2

In [20]:
a1[0]

array([7, 8])

In [21]:
a1[1][0]

9

In [22]:
# create 2-D array using arange()
a=np.arange(20)

In [23]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
a1.shape

(3, 2)

In [25]:
a.ndim

1

In [26]:
a.shape

(20,)

In [27]:
a=a.reshape(5,4)  #change dimension of array

In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
# a[r,c] --slicing
a[1:3:1,0:2:1]

array([[4, 5],
       [8, 9]])

In [30]:
a[2:4:,2:4:]

array([[10, 11],
       [14, 15]])

In [31]:
# 3-D array
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,5,7]]])

In [32]:
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 5, 7]]])

In [33]:
a.ndim

3

In [34]:
a.shape

(2, 2, 3)

In [35]:
# 3-D array with arange
a = np.arange(30)

In [36]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
a.ndim

1

In [38]:
a=a.reshape(3,2,5)

In [39]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [40]:
#a[n,r,c] ---slicing
a[0:2:1,1:2:1,2:4:1]

array([[[ 7,  8]],

       [[17, 18]]])

In [42]:
# 0,4,20,24
a[::2,:1:,::4]

array([[[ 0,  4]],

       [[20, 24]]])